# Deleting all the volume: docker volume rm <volume_name>
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  minio:
    image: minio/minio
    container_name: minio_task_manager
    ports:
      - "9000:9000"   # Storage API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres_db:
    # https://forums.docker.com/t/how-can-i-run-command-into-container/119266 -> Connecting to docker postgres environment
    container_name: postgres_task_manager
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_task_manager
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--requirepass your_password_here --appendonly yes
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
  minio_data:
  esdata01:
  redis-data: