# Generated by Django 6.0.5 on 2026-05-07 09:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assgned_to',
            new_name='assigned_to',
        ),
    ]
