# Generated by Django 6.0.5 on 2026-05-22 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_coment_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by', 'task'], name='projects_at_uploade_b932e9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', 'user'], name='projects_co_task_id_03e7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by', 'created_at'], name='projects_pr_created_53dcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user'], name='projects_pr_user_id_7dfae9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'created_at', 'due_date'], name='projects_ta_created_51a6e8_idx'),
        ),
    ]
