# Generated by Django 6.0.5 on 2026-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_attachment_projects_at_uploade_b932e9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
