export const users = [
  { id: 'u1', name: 'Alex Rivera',  initials: 'AR', color: '#00e5c3', role: 'Product Lead' },
  { id: 'u2', name: 'Priya Mehta',  initials: 'PM', color: '#8b5cf6', role: 'Engineer' },
  { id: 'u3', name: 'Jordan Lee',   initials: 'JL', color: '#f59e0b', role: 'Designer' },
  { id: 'u4', name: 'Sam Chen',     initials: 'SC', color: '#f43f5e', role: 'Engineer' },
  { id: 'u5', name: 'Dana Kim',     initials: 'DK', color: '#38bdf8', role: 'QA' },
];

export const projects = [
  {
    id: 'p1',
    name: 'TeamFlow Platform',
    description: 'Core product development — real-time collaboration & task management.',
    status: 'active',
    color: '#00e5c3',
    members: ['u1', 'u2', 'u3', 'u4'],
    taskCount: 24,
    completedCount: 11,
    dueDate: '2025-08-15',
  },
  {
    id: 'p2',
    name: 'Design System',
    description: 'Unified component library and brand guidelines.',
    status: 'active',
    color: '#8b5cf6',
    members: ['u1', 'u3', 'u5'],
    taskCount: 16,
    completedCount: 9,
    dueDate: '2025-07-01',
  },
  {
    id: 'p3',
    name: 'API Integration',
    description: 'Third-party integrations: Slack, GitHub, Jira connectors.',
    status: 'paused',
    color: '#f59e0b',
    members: ['u2', 'u4'],
    taskCount: 10,
    completedCount: 3,
    dueDate: '2025-09-30',
  },
  {
    id: 'p4',
    name: 'Mobile App',
    description: 'React Native companion app for iOS and Android.',
    status: 'planning',
    color: '#f43f5e',
    members: ['u1', 'u2', 'u3', 'u4', 'u5'],
    taskCount: 8,
    completedCount: 0,
    dueDate: '2025-12-01',
  },
];

export const tasks = [
  {
    id: 't1', projectId: 'p1',
    title: 'WebSocket consumer architecture',
    description: 'Design and implement the Django Channels consumer for real-time project updates.',
    status: 'in_progress', priority: 'urgent',
    assigneeId: 'u2', createdById: 'u1',
    dueDate: '2025-06-10',
    tags: ['backend', 'channels'],
    commentCount: 5,
  },
  {
    id: 't2', projectId: 'p1',
    title: 'Notification bell component',
    description: 'Build the dropdown notification panel with real-time badge updates.',
    status: 'in_progress', priority: 'high',
    assigneeId: 'u3', createdById: 'u1',
    dueDate: '2025-06-08',
    tags: ['frontend', 'ui'],
    commentCount: 2,
  },
  {
    id: 't3', projectId: 'p1',
    title: 'JWT refresh token logic',
    description: 'Implement silent token refresh with retry queue for failed requests.',
    status: 'done', priority: 'high',
    assigneeId: 'u4', createdById: 'u2',
    dueDate: '2025-05-30',
    tags: ['auth', 'backend'],
    commentCount: 8,
  },
  {
    id: 't4', projectId: 'p1',
    title: 'Role-based permission guards',
    description: 'DRF custom permission classes for Owner / Member / Viewer roles.',
    status: 'todo', priority: 'medium',
    assigneeId: 'u2', createdById: 'u1',
    dueDate: '2025-06-20',
    tags: ['backend', 'auth'],
    commentCount: 1,
  },
  {
    id: 't5', projectId: 'p1',
    title: 'File upload to S3',
    description: 'Presigned URL generation and attachment model integration.',
    status: 'todo', priority: 'low',
    assigneeId: 'u4', createdById: 'u1',
    dueDate: '2025-07-01',
    tags: ['backend', 'storage'],
    commentCount: 0,
  },
  {
    id: 't6', projectId: 'p2',
    title: 'Token documentation site',
    description: 'Auto-generate docs from design token JSON using Storybook.',
    status: 'in_progress', priority: 'medium',
    assigneeId: 'u3', createdById: 'u3',
    dueDate: '2025-06-15',
    tags: ['docs', 'design'],
    commentCount: 3,
  },
  {
    id: 't7', projectId: 'p2',
    title: 'Dark mode token audit',
    description: 'Ensure all color tokens have correct dark/light variants.',
    status: 'done', priority: 'high',
    assigneeId: 'u5', createdById: 'u3',
    dueDate: '2025-05-25',
    tags: ['design', 'a11y'],
    commentCount: 4,
  },
  {
    id: 't8', projectId: 'p3',
    title: 'Slack webhook handler',
    description: 'Parse and route Slack events to project notifications.',
    status: 'todo', priority: 'medium',
    assigneeId: 'u2', createdById: 'u2',
    dueDate: '2025-08-10',
    tags: ['integration', 'backend'],
    commentCount: 0,
  },
];

export const notifications = [
  {
    id: 'n1',
    type: 'task_assigned',
    message: 'Priya assigned you to "WebSocket consumer architecture"',
    taskId: 't1', projectId: 'p1',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
    actor: users[1],
  },
  {
    id: 'n2',
    type: 'comment_added',
    message: 'Jordan commented on "Notification bell component"',
    taskId: 't2', projectId: 'p1',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 22),
    actor: users[2],
  },
  {
    id: 'n3',
    type: 'task_done',
    message: 'Sam marked "JWT refresh token logic" as done',
    taskId: 't3', projectId: 'p1',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    actor: users[3],
  },
  {
    id: 'n4',
    type: 'task_assigned',
    message: 'Alex assigned you to "Role-based permission guards"',
    taskId: 't4', projectId: 'p1',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    actor: users[0],
  },
  {
    id: 'n5',
    type: 'comment_added',
    message: 'Dana commented on "Dark mode token audit"',
    taskId: 't7', projectId: 'p2',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    actor: users[4],
  },
];

export const activityFeed = [
  { id: 'a1', actor: users[3], action: 'completed',        target: 'JWT refresh token logic',         time: new Date(Date.now() - 1000 * 60 * 8),       type: 'done' },
  { id: 'a2', actor: users[1], action: 'started working on', target: 'WebSocket consumer architecture', time: new Date(Date.now() - 1000 * 60 * 34),      type: 'progress' },
  { id: 'a3', actor: users[2], action: 'commented on',     target: 'Notification bell component',      time: new Date(Date.now() - 1000 * 60 * 60),      type: 'comment' },
  { id: 'a4', actor: users[4], action: 'completed',        target: 'Dark mode token audit',            time: new Date(Date.now() - 1000 * 60 * 60 * 3),  type: 'done' },
  { id: 'a5', actor: users[0], action: 'created',          target: 'File upload to S3',                time: new Date(Date.now() - 1000 * 60 * 60 * 5),  type: 'create' },
];

export const stats = {
  totalTasks: 58,
  completedThisWeek: 12,
  overdue: 3,
  activeProjects: 2,
  completionByDay: [
    { day: 'Mon', count: 4 },
    { day: 'Tue', count: 6 },
    { day: 'Wed', count: 3 },
    { day: 'Thu', count: 8 },
    { day: 'Fri', count: 7 },
    { day: 'Sat', count: 2 },
    { day: 'Sun', count: 1 },
  ],
};
